version: '3'
services:

  app:
    image: node:latest
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    command: bash -c "cd /app && npm install && npm run start"

  go:
    image: go:latest
    volumes:
      - ./api/go:/api/go
    ports:
      - 8081:8081
    command: bash -c "cd /api/go && go run ./main.go"

  node:
    image: node:latest
    volumes:
      - ./api/node:/api/node
    ports:
      - 8082:8082
    command: bash -c "cd /api/node && npm install && npm run start"

  php:
    image: php:latest
    volumes:
      - ./api/php:/api/php
    ports:
      - 8083:8083
