version: '3'
services:

  # db:
  #   image: mongo:latest

  nginx:
    image: nginx
    volumes:
      - ./frontend/public:/usr/share/nginx/html/
    ports:
      - 80:80

  node:
    image: node:latest
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    command: bash -c "cd /frontend && npm install && npm run start"
