version: '3'
services:
  app:
    image: node:latest
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    command: >
      sh -c "npm run start"

#  go:
#    image: go:latest
#    volumes:
#      - ./api/go:/api/go
#    ports:
#      - 8081:8081
#    command: bash -c "cd /api/go && go run ./main.go"
#
#  node:
#    image: node:latest
#    volumes:
#      - ./api/node:/api/node
#    ports:
#      - 8082:8082
#    command: bash -c "cd /api/node && npm install && npm run start"
#
#  php:
#    image: php:latest
#    volumes:
#      - ./api/php:/api/php
#    ports:
#      - 8083:8083
